modLoader="javafml"
loaderVersion="[46,)"
license="MIT"
issueTrackerURL="https://github.com/Stalemated/mousetweaks-x-accessories-fix/issues"

[[mods]]
modId="mousetweaks_x_accessories_fix"
version="${version}"
displayName="MouseTweaks x Accessories Fix"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mousetweaks-x-accessories-fix"
description="Disables the Wheel Tweak in the Accessories GUI"
authors="Stalemated"
logoFile="assets/mousetweaks-x-accessories-fix/icon.png"

[[mixins]]
config="mousetweaks-x-accessories-fix.client.mixins.json"

[[dependencies.mousetweaks_x_accessories_fix]]
modId="forge"
mandatory=true
versionRange="[46,)"
ordering="NONE"
side="BOTH"

[[dependencies.mousetweaks_x_accessories_fix]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.mousetweaks_x_accessories_fix]]
modId="accessories"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"

[[dependencies.mousetweaks_x_accessories_fix]]
modId="mousetweaks"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"
